# .github/workflows/daily-resume-build.yml
name: Daily Resume & CV Build

on:
  workflow_dispatch:
  schedule:
    # daily at 04:53 UTC → 11:53 PM EST
    - cron: '53 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your Pages repo (so we can commit back to it)
      - name: Check out Pages repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: master

      # 2) Install TeX Live and latexmk
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-xetex \
            texlive-fonts-recommended \
            latexmk

      # 3) Clone the now-public resume repo
      - name: Clone Meza_CV_Resume
        run: git clone https://github.com/anthony-meza/Meza_CV_Resume resume

      # 4) Copy .tex sources into a build folder
      - name: Gather LaTeX sources
        run: |
          mkdir -p paper
          cp resume/Resume.tex paper/Resume.tex
          cp resume/CV.tex     paper/CV.tex

      # 5) Build the PDF with latexmk
      - name: Compile Resume.tex
        run: |
          cd paper
          latexmk -xelatex -interaction=nonstopmode Resume.tex
          latexmk -xelatex -interaction=nonstopmode CV.tex

      # 6) Move the PDF and sources into your files/ folder
      - name: Publish PDF & sources
        run: |
          mv paper/Resume.pdf   files/Resume.pdf
          mv paper/CV.pdf   files/CV.pdf

      # 7) Commit & push only if there’s something new
      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add files/Resume.pdf files/CV.pdf
          git commit -m "CI: update Resume & CV at $(date -u)" || echo "No changes to commit"
          git push origin master
