name: Daily Resume & CV Build

on:
  workflow_dispatch:
  schedule:
    # Daily at 04:00 UTC (midnight EDT)
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your Pages site repo
      - name: Check out Pages repo
        uses: actions/checkout@v4
        with:
          # Keep the GITHUB_TOKEN creds so we can push later
          persist-credentials: true
          ref: master

      # 2) Pull your Meza_CV_Resume repo into `resume/`
      - name: Check out Meza_CV_Resume (private)
        uses: actions/checkout@v4
        with:
          repository: anthony-meza/Meza_CV_Resume
          token: ${{ secrets.RESUME_PAT }}
          path: resume

      # 3) Copy over the .tex files into a build folder
      - name: Gather LaTeX sources
        run: |
          mkdir -p paper
          cp resume/Resume.tex paper/Resume.tex
          cp resume/CV.tex     paper/CV.tex

      # 4) Compile Resume.tex to PDF
      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: paper/Resume.tex

      # 5) Move the generated PDF and the .tex sources into `files/`
      - name: Publish PDF & sources
        run: |
          mv paper/Resume.pdf   files/Resume.pdf
          cp paper/Resume.tex   files/Resume.tex
          cp paper/CV.tex       files/CV.tex

      # 6) Commit & push only if there are changes
      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin \
            https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add files/Resume.pdf files/Resume.tex files/CV.tex
          git commit -m "CI: update Resume & CV at $(date -u)" || echo "No changes to commit"
          git push origin master
